name: neek
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  http: ^0.13.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# 👇 Esta parte va FUERA de cualquier bloque
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_neek.png"


flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
